version: "3.7"

services:

  item-app:
    image: xrerxrerx/item-app
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - item-db

  item-db:
    image: mongo:3
    restart: always
    volumes:
      - app-db:/data/db

volumes:
  app-db:
